Repository criblio/appscope, pull requests merged in 2021-07, with the labels that each got.

#384 Scope flows bug #310
  cli/flows/flow.go
  cli/flows/flow_test.go
Labels: bug

#382 run `make docker-build` as non-root user
  .dockerignore
  .gitignore
  Makefile
  cli/util/proc_test.go
  docker/builder/Dockerfile
  docker/builder/Dockerfile.alpine
Labels: devops

#392 fix hanging alpine tests
  src/wrap.c
Labels: bug, libscope

#390 Fix missing console events (observed when using tls).
  src/transport.c
  src/transport.h
  src/wrap.c
  test/testContainers/docker-compose.override.yml
  test/testContainers/docker-compose.yml
  test/testContainers/transport/Dockerfile
  test/testContainers/transport/README.md
  test/testContainers/transport/cribl/inputs.yml
  test/testContainers/transport/cribl/outputs.yml
  test/testContainers/transport/cribl/pipelines/route.yml
  test/testContainers/transport/docker-entrypoint.sh
  test/testContainers/transport/scope-test
Labels: libscope

#393 Change metric type from counter to timer for http.client.duration and http.server.duration.
  src/httpagg.c
  src/report.c
  test/httpaggtest.c
Labels: libscope

#378 attach failures
  docs/Attach.md
  docs/images/attach1.jpeg
  docs/images/attach2.jpeg
  os/linux/Makefile
  src/fn.c
  src/fn.h
  src/inject.c
  src/scope_static.c
  src/scopeelf.c
  src/scopeelf.h
  src/scopetypes.h
  src/wrap.c
  test/testContainers/cli/expected.yml
  test/testContainers/syscalls/syscall_tests_conf.json
Labels: attach, bug, libscope

#408 Replace dots with underscores in dimensions.
  src/httpagg.c
  test/testContainers/kafka/Dockerfile
Labels: libscope

#413 update changelog for 0.7.1, first round
  README.md
  website/src/data/documentationNav.yaml
  website/src/pages/docs/changelog.md
Labels: documentation

#415 Promote staging to master for the 0.7.1 release
  README.md
  package-lock.json
  website/gatsby-browser.js
  website/gatsby-config.js
  website/package-lock.json
  website/package.json
  website/src/components/MarkDownBlock.js
  website/src/data/documentationNav.yaml
  website/src/pages/docs/changelog.md
  website/src/scss/_documentation.scss
Labels: documentation

#420 Prevent negative numbers in scope prune
  cli/cmd/prune.go
Labels: cli
