Repository criblio/appscope, pull requests merged in 2021-06, with the labels that each got.

#306 Feature/286 tls send
  src/cfg.c
  src/cfg.h
  src/cfgutils.c
  src/scopetypes.h
  src/wrap.c
Labels: libscope

#314 Musl Lib Support
  contrib/libmusl/musl.h
  contrib/tls/tls.h
  os/linux/Makefile
  os/linux/os.c
  src/bashmem.c
  src/bashmem.h
  src/cfgutils.c
  src/fn.c
  src/fn.h
  src/scope.c
  src/scope_static.c
  src/scopeelf.c
  src/scopetypes.h
  src/state.c
  src/sysexec.c
  src/transport.c
  src/utils.c
  src/utils.h
  src/wrap.c
  src/wrap.h
  src/wrap_go.c
  test/cfgutilstest.c
  test/ctltest.c
  test/glibcvertest.c
  test/logtest.c
  test/mtctest.c
  test/testContainers/alpine/Dockerfile
  test/testContainers/alpine/README.md
  test/testContainers/alpine/docker-entrypoint.sh
  test/testContainers/alpine/test_all.sh
  test/testContainers/alpine/test_go.sh
  test/testContainers/alpine/test_tls.sh
  test/testContainers/buildrunall.sh
  test/testContainers/docker-compose.override.yml
  test/testContainers/docker-compose.yml
  test/testContainers/tls/Dockerfile
  test/testContainers/tls/rust/http_test/Makefile
  test/transporttest.c
  website/src/pages/docs/requirements.md
Labels: libscope

#289 adding watch, and log commands and loglevel option
  cli/cmd/logs.go
  cli/cmd/run.go
  cli/cmd/util.go
  cli/cmd/watch.go
  cli/history/sessions.go
  cli/run/run.go
  cli/run/run_test.go
  cli/run/scopeconfig.go
  cli/run/scopeconfig_test.go
  cli/util/util.go
  cli/util/util_test.go
Labels: cli

#298 Attach to a running process from the CLI #292
  cli/cmd/root.go
  cli/cmd/util.go
  cli/go.mod
  cli/go.sum
  cli/run/run.go
Labels: cli

#297 Command line option to define a sym link dir #291
  cli/cmd/util.go
  cli/run/run.go
  cli/run/scopeconfig.go
Labels: cli

#315 attach command
  cli/Makefile
  cli/cmd/attach.go
  cli/cmd/root.go
  cli/cmd/run.go
  cli/cmd/util.go
  cli/cmd/watch.go
  cli/flows/flow_file_test.go
  cli/history/sessions_test.go
  cli/run/run.go
  cli/run/run_test.go
Labels: cli

#323 Removing _dl_sym and the requirement for it when running Splunk. This…
  src/wrap.c
Labels: libscope

#325 Intermittent failures in integ tests from cribl and nginx POST. Added…
  test/testContainers/test_runner/cribl.py
  test/testContainers/test_runner/web.py
Labels: bug, libscope

#339 (#320) Clean up connections to avoid ports stuck in TIME_WAIT.
  src/cfgutils.c
  src/transport.c
  src/transport.h
  test/transporttest.c
Labels: libscope

#343 Attach Integration
  Makefile
  README.md
  cli/Makefile
  cli/cmd/attach.go
  cli/cmd/excrete.go
  cli/cmd/root.go
  cli/cmd/run.go
  cli/cmd/version.go
  cli/cmd/watch.go
  cli/go.mod
  cli/go.sum
  cli/history/sessions.go
  cli/history/sessions_test.go
  cli/internal/config.go
  cli/k8s/webhook.go
  cli/k8s/webhook_test.go
  cli/run/attach.go
  cli/run/run.go
  cli/run/run_test.go
  cli/run/scopeconfig.go
  cli/run/scopeconfig_test.go
  cli/run/setup.go
  cli/run/setup_test.go
  conf/scope.yml
  contrib/Makefile
  docs/README.md
  docs/RELEASE.md
  os/linux/Makefile
  src/inject.c
  src/inject.h
  src/libdir.c
  src/libdir.h
  src/scope.c
  src/scope_static.c
  src/scopeelf.c
  src/scopeelf.h
  src/scopetypes.h
  src/sysexec.c
  src/wrap.c
  test/execute.sh
  test/manual/.gitignore
  test/manual/Makefile
  test/manual/envloop.c
  test/manual/k8s_dev_start.sh
  test/manual/pscoped.sh
  test/options.sh
  test/testContainers/attach/Dockerfile
  test/testContainers/attach/docker-entrypoint.sh
  test/testContainers/attach/expected.yml
  test/testContainers/attach/test_all.sh
  test/testContainers/attach/test_attach.sh
  test/testContainers/buildrunall.sh
  test/testContainers/docker-compose.override.yml
  test/testContainers/docker-compose.yml
  test/testContainers/interposed_func/syscall_tests_conf.json
  test/testContainers/runall.sh
Labels: libscope
