Repository criblio/appscope, pull requests merged in 2021-08, with the labels that each got.

#441 Enable protocol detect events without raw events.
  src/report.c
  src/state.c
Labels: libscope

#447 Provide bash procs with the correct config file
  src/fn.c
  src/fn.h
  src/javaagent.c
  src/utils.c
  src/utils.h
  src/wrap.c
Labels: libscope, attach

#486 Updated the sequence of steps taken on exit.
  src/report.c
  src/report.h
  src/wrap.c
Labels: libscope, known-issue

#512 Feature/489 move protocol
  .github/workflows/build.yml
  cli/Makefile
  cli/cmd/excrete.go
  cli/run/setup.go
  cli/run/setup_test.go
  conf/scope.yml
  conf/scope_protocol.yml
  deploy.sh
  docker/base/Dockerfile
  src/cfgutils.c
  src/cfgutils.h
  src/com.c
  src/com.h
  src/scope_static.c
  src/scopetypes.h
  src/state.c
  test/cfgutilstest.c
  test/testContainers/detect_proto/Dockerfile
  test/testContainers/detect_proto/scope.yml
  test/testContainers/detect_proto/test_protocols.sh
  test/testContainers/http/conf_1/scope.yml
  test/testContainers/http/conf_1/scope_protocol.yml
  test/testContainers/http/conf_2/scope.yml
  test/testContainers/http/conf_2/scope_protocol.yml
  test/testContainers/http/scope-test
Labels: documentation
