Repository criblio/appscope, pull requests merged in 2021-03, with the labels that each got.

#160 Issue 99 http pay extract
  ContainerReadme.md
  conf/scope.yml
  os/linux/os.c
  src/cfg.c
  src/cfg.h
  src/cfgutils.c
  src/ctl.c
  src/ctl.h
  src/evtformat.c
  src/evtformat.h
  src/report.c
  src/runtimecfg.h
  src/scopetypes.h
  src/state.c
  test/cfgutilstest.c
  test/httpheadertest.c
Labels: libscope

#163 (149) Add custom tags to events.
  os/linux/os.c
  src/cfgutils.c
  src/evtformat.c
  src/evtformat.h
  test/evtformattest.c
Labels: libscope

#166 Issue 159 log stream
  conf/scope.yml
  os/linux/os.c
  src/cfg.c
  src/cfg.h
  src/cfgutils.c
  src/cfgutils.h
  src/ctl.c
  src/ctl.h
  src/mtc.c
  src/report.c
  src/scopetypes.h
  src/state.c
  src/utils.c
  src/wrap.c
  test/cfgtest.c
  test/cfgutilstest.c
  test/comtest.c
  test/ctltest.c
  test/evtformattest.c
  test/httpheadertest.c
  test/reporttest.c
  test/testContainers/interposed_func/syscall_tests_conf.json
Labels: libscope

#188 Issue 159 ls config
  conf/scope.yml
  os/linux/Makefile
  os/linux/os.c
  src/cfg.c
  src/cfg.h
  src/cfgutils.c
  src/ctl.c
  src/ctl.h
  src/evtformat.c
  src/evtformat.h
  src/report.c
  test/cfgutilstest.c
  test/httpheadertest.c
Labels: libscope

#190 Create Cribl Dest & move K8S Configs to ConfigMap
  Makefile
  cli/.gitignore
  cli/VERSION
  cli/cmd/excrete.go
  cli/cmd/k8s.go
  cli/cmd/run.go
  cli/cmd/util.go
  cli/go.mod
  cli/go.sum
  cli/k8s/configs.go
  cli/k8s/server.go
  cli/k8s/template.go
  cli/k8s/webhook.go
  cli/k8s/webhook_test.go
  cli/run/run.go
  cli/run/run_test.go
  cli/run/scopeconfig.go
  cli/run/scopeconfig_test.go
  cli/util/newlinereader.go
  docker/demo/Dockerfile
Labels: cli

#195 Added local IP address to the filename for payload data
  src/report.c
Labels: libscope

#194 Go TLS with symbols in metadata
  src/wrap_go.c
Labels: libscope

#184 Logstream integ payheader
  os/linux/Makefile
  os/linux/os.c
  os/linux/os.h
  os/macOS/Makefile
  os/macOS/os.c
  os/macOS/os.h
  src/com.c
  src/com.h
  src/ctl.c
  src/ctl.h
  src/report.c
  src/report.h
  src/state.c
  src/transport.c
  src/wrap.c
  test/comtest.c
  test/manual/reconn.sh
  test/reporttest.c
Labels: libscope

#197 Adding flows command to show network flows and inspect payloads if captured
  cli/cmd/events.go
  cli/cmd/flows.go
  cli/events/events.go
  cli/flows/flow.go
  cli/flows/flow_file_test.go
  cli/flows/flow_test.go
  cli/go.mod
  cli/go.sum
  cli/history/sessions.go
  cli/testscripts/tenKreqs.sh
  cli/util/util.go
Labels: cli

#205 Payload path name with UNIX sockets
  src/report.c
  src/state.c
Labels: libscope

#215 Branches/198 reshape events
  src/ctl.c
  src/ctl.h
  src/evtformat.c
  src/mtcformat.c
  src/report.c
  test/ctltest.c
  test/evtformattest.c
  test/httpheadertest.c
  test/mtcformattest.c
  test/testContainers/buildrunall.sh
  test/testContainers/java/test-ssl.sh
  test/testContainers/runall.sh
  test/testContainers/rungo.sh
Labels: libscope

#219 uptaking new metrics shape
  cli/metrics/metric.go
  cli/metrics/metric_test.go
Labels: cli

#218 Payload short writes
  src/report.c
Labels: libscope

#226 Number of fixes.
  cli/Makefile
  cli/cmd/events.go
  cli/cmd/flows.go
  cli/events/events.go
  cli/flows/flow.go
  cli/flows/flow_file_test.go
  cli/flows/flow_test.go
  cli/flows/gen_flow_test.sh
  cli/run/run.go
  cli/run/scopeconfig.go
Labels: bug, cli

#228 (221) Send custom fields (tags) in ndjson metrics.
  src/mtcformat.c
  test/mtcformattest.c
Labels: libscope

#220 Bugs/dont report funchook
  src/cfgutils.c
  src/wrap.c
Labels: libscope

#231 (224) Fix missing http metrics after latest reshaping effort.
  src/httpagg.c
  test/httpaggtest.c
Labels: libscope
