Repository criblio/appscope, pull requests merged in 2022-10, with the labels that each got.

#1118 Don't emit console events in a musl libc distro when detached.
  src/wrap.c
Labels: libscope, Attach/Detach/Reattach

#1115 Feature/detach go 1088
  src/wrap_go.c
Labels: libscope, Attach/Detach/Reattach

#1094 Allow for detach operation from host directly into container
  src/ns.c
  src/ns.h
  src/scope_static.c
Labels: Attach/Detach/Reattach

#1130 Attach model updates
  os/linux/os.c
  os/linux/os.h
  src/inject.c
  src/inject.h
  src/scope.c
  src/scopetypes.h
  src/wrap.c
Labels: libscope, Attach/Detach/Reattach

#1143 Feature/update profile script
  cli/cmd/start.go
  src/scopetypes.h
  src/setup.c
  test/integration/start/scope-test
  website/src/pages/docs/cli-reference.md
Labels: libscope
