Repository criblio/appscope, pull requests merged in 2022-08, with the labels that each got.

#1057 Feature/got hooking 1039
  os/linux/Makefile
  os/linux/os.c
  src/httpstate.c
  src/javaagent.c
  src/scopeelf.c
  src/scopestdlib.h
  src/state.c
  src/utils.c
  src/wrap.c
  test/integration/metricvariants/scope-test
Labels: libscope

#1062 Attach from the host into the container
  os/linux/Makefile
  src/ns.c
  src/ns.h
  src/scope_static.c
  src/scopestdlib.c
  src/scopestdlib.h
Labels: libscope, attach

#1081 Work around a segfault caused by x86_64 emulation on arm64.
  src/scope.c
  src/sysexec.c
Labels: bug, libscope
