Repository criblio/appscope, pull requests merged in 2023-06, with the labels that each got.

#1506 Docs/1.3.4 Changelog
  website/src/pages/docs/changelog.md
Labels: documentation

#1525 Add mounts to existing containers
  test/manual/mountC.c
Labels: libscope

#1533 Add an implicit allow of runc
  src/wrap.c
  test/integration/attach/Dockerfile.glibc
  test/integration/attach/test_attach.sh
Labels: libscope

#1548 Add close on exec when memfd is created
  os/linux/os.c
Labels: bug, libscope

#1560 Mount the socket dir, not the socket.
  src/cfgutils.c
  test/unit/library/cfgutilstest.c
Labels: libscope
